spring:
  application:
    name: groupmind-application-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

  data:
    mongodb:
      host: localhost
      port: 27017

  jpa:
    hibernate:
      ddl-auto: create

socketio:
  server:
    hostname: localhost
    port: 8085